---
- name: generate ssh key for spark user
  user:
    name: spark
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa

- name: Retrieve spark pub key
  slurp:
    src: "/opt/spark/.ssh/id_rsa.pub"
  register: spark_pubkey
  run_once: true
  delegate_to: localhost

- name: Distribute public key to spark workers
  ansible.posix.authorized_key:
    user: spark
    state: present
    key: "{{ spark_pubkey['content'] | b64decode }}"
  delegate_to: "{{ item }}"
  loop: "{{ groups['spark_workers'] }}"