---
- name: Install NGINX
  apt:
    name: nginx
    state: present

- name: Install apache2-utils for htpasswd
  apt:
    name: apache2-utils
    state: present

- name: Create basic auth password file
  community.general.htpasswd:
    path: /etc/nginx/.htpasswd
    name: "{{ spark_user }}"
    password: "{{ spark_ui_password }}"

- name: Remove default NGINX site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  
- name: Configure NGINX for Spark Master
  template:
    src: nginx_master.conf.j2
    dest: /etc/nginx/sites-available/{{ _domain }}

- name: Enable NGINX configuration on master
  file:
    src: "/etc/nginx/sites-available/{{ _domain }}"
    dest: "/etc/nginx/sites-enabled/{{ _domain }}"
    state: link

- name: Restart NGINX
  service:
    name: nginx
    state: restarted