---
- name: create /opt/spark/.ssh/config for password-less access to workers
  file:
    path: /{{ spark_home }}/.ssh/config
    state: touch
    mode: '0600'
    owner: spark
    group: spark
  become: true

- name: add ssh config for workers to /opt/spark/.ssh/config
  blockinfile:
    path: /{{ spark_home }}/.ssh/config
    block: |
      #jinja2: trim_blocks:False
      {% for server in spark_data.server[1:cluster_size|int] %}
      Host {{ server.instance.ip_pub1 }}
          User spark
          IdentityFile {{ spark_home }}/.ssh/id_rsa 
      {% endfor %}