---
# Create spark system user and group

- name: check if spark group exists
  getent:
    database: group
    key: spark
  ignore_errors: true
  register: groupcheck

- name: create spark group
  group:
    name: spark
    state: present
    system: true
  when: groupcheck is failed

- name: check if spark user exists
  getent:
    database: passwd
    key: spark
  ignore_errors: true
  register: usercheck

- name: create spark user
  user:
    name: spark
    group: spark
    shell: /sbin/nologin
    expires: -1
    create_home: true
    home: "{{ spark_home }}"
    system: true
    state: present
  when: usercheck is failed

- name: set permissions on spark home directory
  file:
    path: "{{ spark_home }}"
    owner: spark
    group: spark
    mode: "0750"