---
# roles/common/tasks/main.yml
# The _domain variable functions as a FQDN to handle deployments using a subdomain, top level domain and www subdomain, or default rDNS. 
# When domain is defined
- name: set dns fact for subdomain
  set_fact:
    _domain: '{{ subdomain }}.{{ domain }}'
    cacheable: yes
  delegate_to: localhost
  run_once: true
  when:
    - domain is defined
    - subdomain != "www"
    
- name: set dns fact for domain
  set_fact:
    _domain: '{{ domain }}'
    cacheable: yes
  delegate_to: localhost
  run_once: true
  when: 
    - domain is defined
    - subdomain == "www"

# When domain is not defined
- name: set dns fact for default rdns
  set_fact:
    _domain: "{{ ansible_default_ipv4.address | replace('.', '-') }}.ip.linodeusercontent.com"
    cacheable: yes
  when: domain is not defined