---
# roles/common/tasks
# common tasks for all linodes
- name: apt update
  apt:
    update_cache: yes

- name: apt upgrade
  apt:
    upgrade: full

- name: install basic packages
  apt:
    pkg:
    - htop
    - rsync
    - strace
    - figlet
    - software-properties-common
    - gnupg2
    - ssl-cert
    - python3-pip
    - python3-venv
    - fail2ban
    - ufw
    state: present

- name: fail2ban jail
  copy:
    src: /etc/fail2ban/fail2ban.conf
    dest: /etc/fail2ban/fail2ban.local
    remote_src: yes
  notify: start fail2ban

# - name: setting up hostname
#   import_tasks: hostname.yml

# dns creation
- name: Create dns A records
  import_tasks: create_dns_record.yml
  run_once: true
  delegate_to: localhost
  when: 
    - token_password is defined
    - domain is defined

- name: secure ssh configs
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.search }}"
    line: "{{ item.replace }}"
  loop:
    - { search: '^\#?PermitRootLogin (yes|no)', replace: 'PermitRootLogin without-password' }
    - { search: '^\#?PasswordAuthentication (yes|no)', replace: 'PasswordAuthentication no' }
    - { search: '^\#?PubkeyAuthentication (yes|no)', replace: 'PubkeyAuthentication yes' }
  notify: restart ssh

# ufw rules 
- name: apply ufw rules
  import_tasks: ufw_rules.yml