---
# set app specific ufw rules 
- name: Allow all access to required ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - 80
    - 443
    - 7077
    - 8080
    - 8081
    - 8480
    - 8481

# async to avoid connection disruption
- name: Enable ufw
  community.general.ufw:
    state: enabled
  async: 60
  poll: 0