---
# set app specific ufw rules 
- name: allow all access to required ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - 80
    - 443

- name: allow access to port 7077 from all cluster nodes
  community.general.ufw:
    rule: allow
    port: 7077
    proto: tcp
    from_ip: "{{ item.instance.ip_priv1 }}"
  loop: "{{ spark_data.server }}"

- name: allow access to port 8081 for worker reverse proxy
  community.general.ufw:
    rule: allow
    port: 8081
    proto: tcp
  delegate_to: "{{ item }}"
  loop: "{{ groups['spark_workers'] }}"

# async to avoid connection disruption
- name: Enable ufw
  community.general.ufw:
    state: enabled
  async: 60
  poll: 0