# roles/post/tasks/main.yml

- name: adding motd to /etc
  import_tasks: motd.yml

- name: adding sudo user
  import_tasks: sudouser.yml

- name: adding user ssh keys
  import_tasks: sshkeys.yml

- name: dumpimg credentials locally
  import_tasks: creds.yml